### ISSUE TITLE
Reporte memoria de calculo

### ISSUE THREAD

**Issue by grovervelasquez** [kplian/sis_presupuestos#1]
Es necesario adicionar un reporte de memorias de calculo que permita filtrar y consolidar por gestion, tipo de presupuesto, presupuesto, categoria programatica, programa y partida.

Ademas de permitir generar en PDF o EXCEL.
Adjunto un ejemplo.

![image](https://cloud.githubusercontent.com/assets/18399403/14716422/f26dcdbe-07ba-11e6-8a66-b3acb078fc8d.png)

![image](https://cloud.githubusercontent.com/assets/18399403/14677254/d67a6c20-06de-11e6-85bb-73f09e00bb10.png)

**Comment by rensi4rn** [comment]
Hecho
![image](https://cloud.githubusercontent.com/assets/2071383/14752818/67ab3668-089f-11e6-83dd-f66325d6232e.png)

**Comment by rensi4rn** [comment]
Listo reporte en excel
![image](https://cloud.githubusercontent.com/assets/2071383/14820688/ae870294-0b95-11e6-8989-6d27120324e3.png)
