### ISSUE TITLE
Reporte formulacion presupuestaria

### ISSUE THREAD

**Issue by grovervelasquez** [kplian/sis_presupuestos#2]
Es necesario elaborar un reporte con el detalle mensual de la formuacion, que permita filtrar por tipo de presupuesto, categoria programatica, programa, presupuesto y diferentes tipos de niveles de agrupacion (Solo grupos, Grupos y patidas de movimiento, Solo partidas de movimiento, Todos los niveles)

![image](https://cloud.githubusercontent.com/assets/18399403/14716162/c05625ca-07b9-11e6-812b-bbefb3c76851.png)

El reporte final debe poder generarce en PDF y Excel.

![image](https://cloud.githubusercontent.com/assets/18399403/14716237/0e26e47e-07ba-11e6-9a17-4acfba86e37a.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/14858246/45d9ffde-0c6d-11e6-8011-07a9e2c30aab.png)

**Comment by grovervelasquez** [comment]
al sacar el nuevo reporte por Categoria Programatica sale el siguiente mensaje:

Mensaje: column p.id_categoria_programatica does not exist
Capa: base
Origen: driver.php
Procedimiento: pre.f_rep_programacion
Transacción: PRE_PROGR_REP

Al sacar el reporte por Programa o por Presupuesto abre una pestaña en blanco.

Creo que demas de los filtros actuales, seria bueno agregar un combo que permita obtener el reporte Detallado o Resumido.

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/14859623/f783236e-0c72-11e6-9893-dd1f753d0343.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/14860607/a8ff24a4-0c77-11e6-9e19-f624236ec369.png)

**Comment by rensi4rn** [comment]
Agregar el detallado seria mucho cambio , por ahora dejemoslo asi 
para pasar a otras cosas más prioritarias
lo podemos hacer más adelante
