### ISSUE TITLE
Reporte ejecucion presupuestaria

### ISSUE THREAD

**Issue by grovervelasquez** [kplian/sis_presupuestos#3]
Es necesario habilitar un reporte que permita generar la siguiente informacion en PDF y Excel, ya sea desagregado por presupuesto o consolidado por empresa, categoria programatica o programa.

![image](https://cloud.githubusercontent.com/assets/18399403/14723413/0201746e-07df-11e6-87aa-3ef3fd0146f8.png)

![image](https://cloud.githubusercontent.com/assets/18399403/14723200/d59ad31c-07dd-11e6-93f9-fba475125434.png)

![image](https://cloud.githubusercontent.com/assets/18399403/14723249/12c7e14e-07de-11e6-9cca-236a02cc60d6.png)

Encontre algo similar en una de las grillas del sistema pero no permite consolidar a diferentes niveles con se puede hacer en el reporte.

![image](https://cloud.githubusercontent.com/assets/18399403/14723387/dbb24a90-07de-11e6-8c42-863f84c3016f.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/14864119/81d15b68-0c86-11e6-9a28-99b0e8e6ece3.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/14897001/2b75738a-0d4e-11e6-9c6b-2d317999de79.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/14897727/4f63fba6-0d51-11e6-9000-758d6c4390e2.png)
