### ISSUE TITLE
Unidad de medida en la cabecera de memoria y no en el detalle

### ISSUE THREAD

**Issue by grovervelasquez** [kplian/sis_presupuestos#5]
El dato de la unidad de medida debería ir en la cabecera de la memoria de calculo ya que un concepto solo debería estar relacionado a una unidad y no a varias. 

![image](https://cloud.githubusercontent.com/assets/18399403/14787102/ff7898dc-0acf-11e6-838a-fad515e43a49.png)

Como esta actualmente incluso ocasiona que en el reporte de memoria de calculo aparescan datos con total Cero ya que agrupa por unidad de medida y suma las cantidades aunque no tenga importes.

![image](https://cloud.githubusercontent.com/assets/18399403/14787129/1d714ab4-0ad0-11e6-89b9-9bf047adfb74.png)

**Comment by rensi4rn** [comment]
La precio unitario cero es solo por que no llene datos en todos lo registros,
solo un par para probar.

la unidad de medida si tiene que ir en el detalle por que la unidad puede variar de un mes a otros,  mismo al consolidar presupuestos, asi es mas flexible.

no va dar  problemas en el reporte por que se agrupa según unidad de medida
