### ISSUE TITLE
Reporte ejecucion por partida

### ISSUE THREAD

**Issue by grovervelasquez** [kplian/sis_presupuestos#6]
Es necesario generar un reporte que muestre el detalle de ejecución de alguna partida específica.

![image](https://cloud.githubusercontent.com/assets/18399403/14789096/06721ed4-0ad9-11e6-8c02-49892759ecbb.png)

El resultado obtenido seria algo asi

![image](https://cloud.githubusercontent.com/assets/18399403/14789247/a61a9bdc-0ad9-11e6-9929-fe5eacd629aa.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/14920246/814710be-0dfa-11e6-9216-8ca63f859550.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/14920271/95f7bc70-0dfa-11e6-91f2-d0c0c181796d.png)
